// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spotify.API.DbContexts;

#nullable disable

namespace Spotify.API.Migrations
{
    [DbContext(typeof(PlaylistInfoContext))]
    partial class PlaylistInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Spotify.API.Entities.Cancion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("Canciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Queen.",
                            Name = "I want it all",
                            PlaylistId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Estopa.",
                            Name = "Vino tinto",
                            PlaylistId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "choppin.",
                            Name = "piano1",
                            PlaylistId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "choppin.",
                            Name = "piano2",
                            PlaylistId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sebastián Yatra.",
                            Name = "Tacones rojos",
                            PlaylistId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "Rosalia.",
                            Name = "La fama",
                            PlaylistId = 3
                        });
                });

            modelBuilder.Entity("Spotify.API.Entities.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Canciones para escuchar en el coche.",
                            Name = "lista coche"
                        },
                        new
                        {
                            Id = 2,
                            Description = "lista de canciones de piano para concentrarse.",
                            Name = "Concentración"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lista de 50 canciones más escuchadas.",
                            Name = "Más escuchadas"
                        });
                });

            modelBuilder.Entity("Spotify.API.Entities.Cancion", b =>
                {
                    b.HasOne("Spotify.API.Entities.Playlist", "Playlist")
                        .WithMany("Canciones")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Spotify.API.Entities.Playlist", b =>
                {
                    b.Navigation("Canciones");
                });
#pragma warning restore 612, 618
        }
    }
}
